### ISSUE TITLE
Falsy values are treated as `Array` type

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/is#131]
```js
const is = require('@sindresorhus/is');

is.assert.any([is.urlInstance], undefined);
```

Actual:

```
TypeError: Expected value which is `predicate returns truthy for any value`, received value of type `Array`.
```

Expected:

```
TypeError: Expected value which is `predicate returns truthy for any value`, received value of type `undefined`.
```

**Comment by sindresorhus** [comment]
// @scraggo

**Comment by szmarczak** [comment]
The same happens with `false`, `0`, `null`, `NaN`.

**Comment by scraggo** [comment]
I'd like to take a look at this.

**Comment by scraggo** [comment]
Started looking into it.

[`assert.any`](https://github.com/sindresorhus/is/blob/main/source/index.ts#L623) ([source](https://github.com/sindresorhus/is/blob/main/source/index.ts#L623)) gathers (with the spread operator) the 2nd argument, `values`. It then calls `assertType` with that gathered array as the 3rd argument.

```
any: (predicate: Predicate | Predicate[], ...values: unknown[]): void | never => 
// values is an array and evaluated as such in `assertType`:
assertType(is.any(predicate, ...values), AssertionTypeDescription.any, values),
```

So, that's why the message always fails with `Array` type. Given this, _any_ failure (not just falsy values and not just predicate arrays) have the same incorrect message:

```
assert.any([is.string], 1);
assert.any(is.string, 1);
```

At the moment, I'm not sure how to address this, but I think that's the crux of the issue.

**Comment by scraggo** [comment]
@sindresorhus Hi maintainers! I opened a [PR](https://github.com/sindresorhus/is/pull/132) to address this.
