### ISSUE TITLE
`directInstanceOf()` method

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/is#36]
Sometimes it's useful to be able to check if something is a direct instance of a class. `instanceOf` also matches any subclasses of that type, which is not always desirable.

```js
const directInstanceOf  = (instance, klass) => Object.getPrototypeOf(instance) === klass.prototype;
```

It's not a lot of code, but I always forget how to do it properly, so would be nice to have a check for this.

**Comment by brandon93s** [comment]
`klass` - I see this as a naming "convention" back to the jQuery plugin. Curious what the origin of the "k" is, and/or what is stands for? With the answer to that in mind, do we want to go with "k" in the implementation?

**Comment by sindresorhus** [comment]
@brandon93s `class` is a reserved keyword. Happy to consider other workarounds. Wish we could just quote it somehow. Like in Swift, we can just wrap reserved keywords in backticks to have it work.

**Comment by vtgn** [comment]
> Sometimes it's useful to be able to check if something is a direct instance of a class. `instanceOf` also matches any subclasses of that type, which is not always desirable.
> 
> ```js
> const directInstanceOf  = (instance, klass) => Object.getPrototypeOf(instance) === klass.prototype;
> ```
> 
> It's not a lot of code, but I always forget how to do it properly, so would be nice to have a check for this.

Hello,

I reopen this issue because this implementation of the _directInstanceOf_ function doesn't work if the given instance is null or undefined, and throws the error :"TypeError: Cannot convert undefined or null to object" because the Object.getPrototypeOf method doesn't allow undefined or null as argument.

It would really be more practical to modify the implementation of the _directInstanceOf_ function to return _false_ if 

> instance === null || instance === undefined.

Regards.
